ar-io/arns-react

src/App.tsx
As per dylan request re: unpublished review comment on previous PR from ARNS-home-screen
=> chore(routing): move dot route to bottom of route list and change 'home' route to '/'

src/components/icons/index.ts, src/components/inputs/Search/SearchBar/SearchBar.tsx, src/components/inputs/Search/SearchBar/__tests__/SearchBar.test.tsx, src/components/inputs/Search/SearchBar/styles.css, src/components/layout/Footer/Footer.tsx, src/components/layout/SearchBarFooter/SearchBarFooter.tsx, src/components/layout/SearchBarFooter/styles.css, src/components/layout/SearchBarHeader/SearchBarHeader.tsx, src/components/modals/ConnectWalletModal/ConnectWalletModal.tsx, src/components/pages/Home/Home.tsx, src/index.css, src/types.ts, types/constants.ts
=> feat(regExp): Search bar name regex and error component

src/components/cards/AntCard/AntCard.tsx, src/components/cards/AntCard/styles.css, src/index.css
=> feat(detailsCard): Fix ant details card

package-lock.json, package.json, src/App.tsx, src/components/inputs/Search/SearchBar/SearchBar.tsx, src/components/inputs/buttons/ConnectButton/ConnectButton.tsx, src/components/layout/Navbar/NavGroup/NavGroup.tsx, src/components/layout/UpgradeTier/UpgradeTier.tsx, src/components/modals/ConnectWalletModal/ConnectWalletModal.tsx, src/hooks/useConnectWalletModal/useConnectWalletModal.tsx, src/services/wallets/ArConnectWalletConnector.ts, src/services/wallets/ArconnectWalletConnector.ts, src/services/wallets/JsonWalletConnector.ts, src/services/wallets/index.ts, src/state/reducer.ts, src/state/state.tsx, src/types.ts
- Allows user to connect wallet via arconnect
- Updates global state variables to use abstracted ArweaveWalletConnector class
=> feat: integrate arconnect

.github/workflows/build_and_test.yml
Sends deploy notifications to #arns-app-builds
=> chore: add slack notifications

package-lock.json, package.json, src/components/cards/AntCard/AntCard.tsx, src/components/cards/NavMenuCard/NavMenuCard.tsx, src/components/inputs/Search/SearchBar/SearchBar.tsx, src/components/layout/Loader/Loader.tsx, src/components/layout/index.ts
Creates a simple loader with `react-loader-spinner` lib. This can be replaced once we have feedback for loading indicators.
=> feat: introduce a simple loading component

src/components/cards/NavMenuCard/NavMenuCard.tsx, src/services/arweave/ArweaveCompositeDataProvider.ts, src/services/arweave/LocalFilesystemDataProvider.ts, src/services/arweave/WarpDataProvider.ts, src/types.ts
=> feat: fetch contract balance from warp data provider

src/App.tsx, src/components/inputs/Search/SearchBar/SearchBar.tsx, src/components/inputs/Search/SearchBar/__tests__/SearchBar.test.tsx, src/components/inputs/Search/SearchBar/styles.css, src/components/inputs/buttons/WorkflowButtons/WorkflowButtons.tsx, src/components/layout/ConfirmRegistration/ConfirmRegistration.tsx, src/components/layout/Navbar/Navbar.tsx, src/components/layout/RegisterNameForm/RegisterNameForm.tsx, src/components/layout/SearchBarFooter/SearchBarFooter.tsx, src/components/layout/SuccessfulRegistration/SuccessfulRegistration.tsx, src/components/layout/UpgradeTier/UpgradeTier.tsx, src/components/layout/Workflow/Workflow.tsx, src/components/pages/Home/Home.tsx, src/index.css, src/state/contexts/GlobalState.tsx, src/state/contexts/RegistrationState.tsx, src/state/reducers/GlobalReducer.ts, src/state/reducers/RegistrationReducer.ts, src/types.ts, src/utils/searchUtils.ts
- moves registration state to wrap `Home` to allow us to set on change events from the workflow component
- fix some small syntax issues reported from demo
- disable `Next` in registration flow via `disableNext` attribute
- add `validationErrors` when providing an ANT ID
=> feat: registration updates

package-lock.json, package.json, src/components/pages/Manage/Manage.tsx, src/hooks/useWalletAddress/useWalletAddress.tsx, src/services/wallets/ArConnectWalletConnector.ts
- fix: wallet address was not updating in menu when switching arconnect wallets
- chore: use async/await for fetching ants, add TODO
=> fix: wallet fix in nav menu, ant fetching

src/components/cards/TierCard/styles.css, src/components/inputs/Counter/Counter.tsx, src/components/inputs/Counter/styles.css, src/components/inputs/Search/SearchBar/SearchBar.tsx, src/components/inputs/Search/SearchBar/styles.css
- fix: update search input type, add keyHint
- fix: counter button size, hover effect
=> fix: search bar type, small design nits on counter buttons

src/components/inputs/buttons/CopyTextButton/CopyTextButton.tsx, src/components/layout/tables/AntRow/AntRow.tsx, src/components/layout/tables/AntTable/AntTable.tsx, src/components/pages/Manage/Manage.tsx
added interval to update transaction confirmations every 30 seconds, and added refresh button to ant table
=> chore: Demo jan 18 recs

src/components/cards/AntCard/AntCard.tsx, src/components/cards/AntCard/styles.css
Cleans up AntCard to use a table - I should've done this in the first place to keep formatting easy
=> fix: use table in AntCard

src/App.tsx
- fix: use hash router to preserve urls and better manage history
- chore: remove vite config for browser router
=> fix: use HashRouter

src/components/cards/NavMenuCard/NavMenuCard.tsx, src/components/cards/NavMenuCard/styles.css, src/utils/routes.ts
=> feat: update nav menu

src/components/layout/Workflow/Workflow.tsx, src/components/modals/ConnectWalletModal/ConnectWalletModal.tsx, src/components/modals/CreateAntModal/CreateAntModal.tsx, src/components/pages/Home/__tests__/Home.test.tsx
- fix: update connect wallet button
- fix: modal route bugs
=> fix(PE-3291): some small scroll bugs

src/components/layout/TransactionWorkflow/TransactionWorkflow.tsx, src/components/modals/ManageAntModal/ManageAntModal.tsx, src/types.ts, src/utils/transactionUtils/transactionUtils.ts
example transaction: https://viewblock.io/arweave/tx/btNwLXV9aqtja_8R3tRcD2DBVTV9Iyn4sPC-O76kX_o
=> feat(PE-3363): edit targetID config

src/components/layout/ArPrice/ArPrice.tsx, src/components/layout/TransactionWorkflow/TransactionWorkflow.tsx, src/components/modals/ManagePDNTModal/ManagePDNTModal.tsx, src/components/modals/TransferPDNTModal/TransferPDNTModal.tsx, src/index.css, src/types.ts, src/utils/transactionUtils/transactionUtils.ts
example tx https://viewblock.io/arweave/tx/RiBwI9Jq57vbAIWl_OO26FdEEm9fAXQmOCpTs8M0feg
=> Feat(PE-3364): transfer PDNT

src/components/layout/ConfirmRegistration/ConfirmRegistration.tsx, src/components/layout/RegisterNameForm/RegisterNameForm.tsx, src/components/layout/SuccessfulRegistration/SuccessfulRegistration.tsx, src/components/layout/TransactionWorkflow/TransactionWorkflow.tsx, src/hooks/useArweaveCompositeProvider/useArweaveCompositeProvider.tsx, src/services/arweave/SimpleArweaveDataProvider.ts, src/services/arweave/WarpDataProvider.ts, src/state/contexts/GlobalState.tsx
Leverages the `ar-io.dev` gateway for fetching/publishing new transactions.
=> feat(PE-3615): use ar-io.dev gateway by default

src/components/cards/PDNSCard/PDNSCard.tsx, src/components/cards/PdnsCard/styles.css, src/components/layout/Undernames/Undernames.tsx, src/components/modals/CreatePDNTModal/CreatePDNTModal.tsx, src/index.css
Includes some other small design cleanup things.
=> fix(PE-3617): fix featured domains links and meta tags

src/components/cards/PDNSCard/styles.css, src/components/layout/Undernames/Undernames.tsx, src/components/modals/DialogModal/DialogModal.tsx, src/hooks/useUndernames/useUndernames.tsx, src/types.ts
=> feat(PE-3541): Added edit/remove/create undername modal to undernames table

index.html, src/components/layout/TransactionComplete/TransactionComplete.tsx, src/components/layout/Undernames/Undernames.tsx, src/utils/transactionUtils/transactionUtils.ts
note: currently the gateway is set to use ar-io.dev - this occasionally has issues on the gateway side with posting transactions, if so just change the gateway url in GlobalState.tsx to arweave.net, and it should work.
=> Feat(PE-3643): add create undername interaction

src/components/layout/TransactionComplete/TransactionComplete.tsx
=> fixit(PE-3065): remove sonar link

src/components/cards/PDNSCard/PDNSCard.tsx, src/components/cards/PDNSCard/styles.css, src/components/cards/PdnsCard/styles.css, src/components/layout/FeaturedDomains/FeaturedDomains.tsx, src/components/layout/FeaturedDomains/styles.css, src/components/layout/Footer/Footer.tsx, src/index.css
updates the featured domains component and arns card (pdns card) component to match figma,
Threw in a mobile fix for the wonky footer as well.
=> Feat(PE-3950): update featured domains and arns cards

src/components/cards/PDNTCard/PDNTCard.tsx, src/components/inputs/Search/SearchBar/SearchBar.tsx, src/components/inputs/Search/SearchBar/styles.css, src/components/layout/SearchBarFooter/SearchBarFooter.tsx, src/components/pages/Home/Home.tsx, src/components/pages/Transaction/Transaction.tsx, src/utils/transactionUtils/transactionUtils.ts
=> feat(PE-3883): updated ant card to match figma

.github/workflows/build_and_test.yml, src/hooks/useArweaveCompositeProvider/useArweaveCompositeProvider.tsx, src/vite-env.d.ts
We'll likely make these env specific vars, but fine for now
=> chore: update api and arweave host to env vars

firebase.json, src/components/cards/ValidationList/ValidationList.tsx, src/components/inputs/Search/SearchBar/SearchBar.tsx, src/components/inputs/Search/SearchBar/__tests__/SearchBar.test.tsx, src/components/inputs/Search/SearchBar/styles.css, src/components/inputs/text/ValidationInput/ValidationInput.tsx, src/components/layout/SearchBarFooter/SearchBarFooter.tsx, src/components/layout/SearchBarFooter/__tests__/SearchBarFooter.test.tsx, src/components/layout/SearchBarFooter/__tests__/SearchBarFooter.tsx, src/components/layout/SearchBarHeader/SearchBarHeader.tsx, src/components/layout/Workflow/Workflow.tsx, src/components/pages/Home/Home.tsx, src/index.css, src/types.ts, src/utils/constants.ts
=> feat(PE-3970): update searchbar design

.github/workflows/build_and_test.yml, .github/workflows/pr.yml, .github/workflows/production.yml, package.json, src/state/contexts/GlobalState.tsx, src/state/contexts/WalletState.tsx, src/utils/constants.ts, src/vite-env.d.ts, yarn.lock
Network request using cu.ar-io.dev:
=> fix(ao): support providing AO_CU_URL on build

jest.config.json, package.json, src/components/forms/DomainSettings/SourceCodeIdRow.tsx, src/components/modals/ant-management/UpgradeAntModal/UpgradeAntModal.tsx, src/components/modals/ant-management/UpgradeAntsModal/UpgradeAntsModal.tsx, src/hooks/useANTLuaSourceCode.tsx, src/state/actions/dispatchArIOInteraction.ts, src/state/contexts/ArNSState.tsx, src/utils/constants.ts, yarn.lock
There were a few conflicts so creating this branch to validate develop ends up as expected.
=> chore: main back to develop

src/components/inputs/DomainSearch.tsx, src/components/inputs/Search/HomeSearch.tsx
https://www.loom.com/share/267cedf53ee24b9388982cc7842d3cfa?sid=ab3c5fe3-48fa-409b-98f6-d2f90aae7b02
=> feat(PE-6889): add click out behaviour to home search

src/components/layout/UpgradeUndernames/UpgradeUndernames.tsx, src/components/pages/Transaction/transaction-headers.tsx
* Fixes showing price in IO (rather than mIO) for Increase Undernames Flow
* Also fixes header formatting for Transaction Review pages for Increase Undernames and Extend Lease flows
=> Fix-io-price

CHANGELOG.md, src/components/data-display/tables/ReturnedNamesTable.tsx, src/components/layout/FeaturedDomains/FeaturedDomains.tsx, src/components/layout/Footer/Footer.tsx, src/components/pages/ManageDomain/ManageDomain.tsx
- Added Start Date column in Return Name Table
- Updated Return Name Table to use left-hand arrow button for expand/collapse of chart
- Minor visual improvements (spacing, colors, etc.)
=> PE-7688: ArNS polish quick wins

package.json, src/components/cards/NavMenuCard/NavMenuCard.tsx, src/hooks/useTurboArNSClient.tsx, src/hooks/useTurboCreditBalance.tsx, src/services/arweave/TurboArNSClient.ts, src/utils/constants.ts, yarn.lock
Verify the target branch before merging - need to discuss if this is an all-at-once feature or iterative
=> feat(PE-7852): add turbo credit balance to nav card

CHANGELOG.md, package.json, src/state/actions/dispatchANTInteraction.ts, src/state/actions/dispatchArIOInteraction.ts
Includes Referrer and App-Name/App-Version tags added to various write API's
=> Release 1.14.2

CHANGELOG.md, package.json, src/components/data-display/tables/DomainsTable.tsx, src/components/data-display/tables/UndernamesTable.tsx, src/components/forms/DomainSettings/ControllersRow.tsx, src/components/forms/DomainSettings/DomainSettings.tsx, src/components/forms/DomainSettings/OwnerRow.tsx, src/components/modals/PrimaryNameModal/PrimaryNameModal.tsx, src/components/pages/Register/Register.tsx, src/hooks/useArNSIntentPrice.tsx, src/hooks/usePrimaryName.tsx, src/state/contexts/TransactionState.tsx, src/utils/routes.tsx
Replaces custom upgrade logic with the `upgrade` API available in `ar-io-sdk@v3.19.0`
=> chore: release v1.25.0
